server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/project-kttkpm-01-Note-User/cloud-config-server.git
          default-label: main
        bootstrap: false
        clone-on-start: true